version: '2'

services:

  web:
    restart: always
    build: ./web
    networks:
      - front-tier
      - back-tier
    volumes:
      - /media/lee/78b3df3f-70e8-4101-b632-d3b341665d5f/mycodebase/Dockerizing-pgAdmin-with-Compose/web:/usr/src/app
    command: /usr/local/bin/gunicorn wsgi:application -w 2 -b :5050

  nginx:
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    networks:
      - front-tier

  postgres:
    image: postgres:latest
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/
    networks:
      - back-tier 

volumes: 
  pgdata:

networks:
  front-tier:
  back-tier: